//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeScreenResolution.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChangeScreenResolution.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings change was unsuccessful because system is DualView capable..
        /// </summary>
        internal static string InvalidOperation_Disp_Change_BadDualView {
            get {
                return ResourceManager.GetString("InvalidOperation_Disp_Change_BadDualView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid set of flags was passed in..
        /// </summary>
        internal static string InvalidOperation_Disp_Change_BadFlags {
            get {
                return ResourceManager.GetString("InvalidOperation_Disp_Change_BadFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graphics mode is not supported..
        /// </summary>
        internal static string InvalidOperation_Disp_Change_BadMode {
            get {
                return ResourceManager.GetString("InvalidOperation_Disp_Change_BadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid parameter was passed in. This can include an invalid flag or combination of flags..
        /// </summary>
        internal static string InvalidOperation_Disp_Change_BadParam {
            get {
                return ResourceManager.GetString("InvalidOperation_Disp_Change_BadParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display driver failed the specified graphics mode..
        /// </summary>
        internal static string InvalidOperation_Disp_Change_Failed {
            get {
                return ResourceManager.GetString("InvalidOperation_Disp_Change_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write settings to the registry..
        /// </summary>
        internal static string InvalidOperation_Disp_Change_NotUpdated {
            get {
                return ResourceManager.GetString("InvalidOperation_Disp_Change_NotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer must be restarted in order for the graphics mode to work..
        /// </summary>
        internal static string InvalidOperation_Disp_Change_Restart {
            get {
                return ResourceManager.GetString("InvalidOperation_Disp_Change_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error..
        /// </summary>
        internal static string InvalidOperation_FatalError {
            get {
                return ResourceManager.GetString("InvalidOperation_FatalError", resourceCulture);
            }
        }
    }
}
